### ISSUE TITLE
ISPBOOT.BIN

### ISSUE THREAD

**Issue by cu6apum** [tibbotech/br2_external#1]
Hi there, have built everything just fine.
The target was SDCard, got a 70 meg file starting with XBUT.

Dumb question: what is it? It's neither an image to flash (no partition table), nor a filesystem. According to makefile, it has to have everything inside - boot, dtb, kernel, and even a root fs, - but what's the way to have it sent it to the board?

Thanks in advance.

PS. The BR layer looks in fact very quick-n-dirty, no board package / genimage, thus weird image format. Investigating now...

**Comment by dmitrydvorkin** [comment]
ISPBOOOT.BIN is the file that is understandable by xboot (pre-u-boot) and u-boot bootloaders.
It has extra header and looks like partitioned disk.
U-Boot knows where parts are located and able to unpack and write parts into target storage.
This file is the firmware upgrade source.

1) This file should be copied to SD or USB FAT-formatted flash
2) wire CN10 and CN11 jumper (if you have this file on SD) or wire CN11 jumper (if you put this file on USB)
3) insert SD or USB flash into device and reset the board

bootloader reads file, checks it and writes block-by-block.

> The BR layer looks in fact very quick-n-dirty, 
- simply because most users has it's own way to cook the BR. Sometimes too much different.

if you want to make it better - I'll be glad if you'll commit your updates!

**Comment by cu6apum** [comment]
Sorry, I did not get that the image is dedicated for some proprietary board upgrade. Tried to make a regular bootable sd for bPi f2p.
Now trying to find out how to. And possibly will brush the layer later.
